import json

batch = 'pla_batch_039'
ts = '2026-04-17T00:00:00.000000+08:00'

entries = [
{'source_file': 'E:/\u6295\u8cc7\u4ea4\u6613/pla_md/logic/Herman002_TX_CDP_LT (3).md', 'strategy_name': 'Herman002_TX_CDP20210615_LT_dup3', 'family': 'Herman/CDP series', 'timeframe': 'Intraday (time>=0900, SetExitOnClose)', 'direction': 'Both', 'category': 'CDP pivot multi-level breakout with CountIf confirmation (dup3)', 'summary': 'Herman002_TX_CDP20210615_LT (copy 3) -- Identical to base. Deduped.'},
{'source_file': 'E:/\u6295\u8cc7\u4ea4\u6613/pla_md/logic/Herman002_TX_CDP_LT (4).md', 'strategy_name': 'Herman002_TX_CDP20210615_LT_dup4', 'family': 'Herman/CDP series', 'timeframe': 'Intraday (time>=0900, SetExitOnClose)', 'direction': 'Both', 'category': 'CDP pivot multi-level breakout with CountIf confirmation (dup4)', 'summary': 'Herman002_TX_CDP20210615_LT (copy 4) -- Identical to base. Deduped.'},
{'source_file': 'E:/\u6295\u8cc7\u4ea4\u6613/pla_md/logic/Herman002_TX_CDP_LT.md', 'strategy_name': 'Herman002_TX_CDP20210615_LT_base', 'family': 'Herman/CDP series', 'timeframe': 'Intraday (time>=0900, SetExitOnClose)', 'direction': 'Both', 'category': 'CDP pivot multi-level breakout with CountIf confirmation (base)', 'summary': 'Herman002_TX_CDP20210615_LT (base) -- CDP=(H1+L1+2*C1)*0.25. AH=CDP+(H1-L1); NH=2*CDP-L1; AL=2*CDP-H1; NL=CDP-(H1-L1). B1: narrow-range day + time>=0900 + no prior entry -> stop at HighD(0). B2: CountIf(c>AH,5)>=4 -> stop at AL (persistent bulls). B2a: CountIf(c<AL,5)>=4 -> stop at AH (reversion). B3: add on narrow range -> HighD(0)-3. S mirrors. Limit exit closeD(1)*1.07. Key insight: close-weighted CDP more responsive than OHLC/3; 4-of-5 persistence reduces false breakouts; dual-mode B1/B2a captures both regimes.'},
{'source_file': 'E:/\u6295\u8cc7\u4ea4\u6613/pla_md/logic/HiSKIO\u7c4c\u78bc\u7a0b\u5f0f\u4ea4\u6613\u7a0b\u5f0f\u78bc.md', 'strategy_name': 'b40MC3_FINI_MeanReversion', 'family': 'FINI/Institutional flow series', 'timeframe': 'Unknown (SetExitOnClose)', 'direction': 'Both', 'category': 'RSI mean-reversion on FINI institutional flow indicator', 'summary': 'b40MC3 FINI strategy -- RSI(FINI,5). Entry on RSI cross when marketposition=0. Exit: entryprice+/-TG limit. Key insight: FINI = Foreign Institutional Net Investment (Taiwan). RSI on institutional flow = measuring flow momentum not price; mean-reversion on extreme institutional positioning bets on flow self-correction.'},
{'source_file': 'E:/\u6295\u8cc7\u4ea4\u6613/pla_md/logic/Homework20200718 (2).md', 'strategy_name': 'Homework20200718_dup2', 'family': 'Homework series', 'timeframe': 'Intraday', 'direction': 'Both', 'category': 'Gap + daily OHLC momentum entry with overheat bar-count exit (dup2)', 'summary': 'Homework20200718 (copy 2) -- Deduped.'},
{'source_file': 'E:/\u6295\u8cc7\u4ea4\u6613/pla_md/logic/Homework20200718 (3).md', 'strategy_name': 'Homework20200718_dup3', 'family': 'Homework series', 'timeframe': 'Intraday', 'direction': 'Both', 'category': 'Gap + daily OHLC momentum entry with overheat bar-count exit (dup3)', 'summary': 'Homework20200718 (copy 3) -- Deduped.'},
{'source_file': 'E:/\u6295\u8cc7\u4ea4\u6613/pla_md/logic/Homework20200718 (4).md', 'strategy_name': 'Homework20200718_dup4', 'family': 'Homework series', 'timeframe': 'Intraday', 'direction': 'Both', 'category': 'Gap + daily OHLC momentum entry with overheat bar-count exit (dup4)', 'summary': 'Homework20200718 (copy 4) -- Deduped.'},
{'source_file': 'E:/\u6295\u8cc7\u4ea4\u6613/pla_md/logic/Homework20200718.md', 'strategy_name': 'Homework20200718_base', 'family': 'Homework series', 'timeframe': 'Intraday (bar-interval dependent)', 'direction': 'Both', 'category': 'Gap within 2-day range momentum entry with overheat bar-count exit', 'summary': 'Homework20200718 (base) -- gap-up AND gap < 2-day range = non-exhaustion gap. k=2 -> buy; k=1 AND condition30 -> sell. BT-OVERHEAT: countH/countL>=BTOH -> exit. Key insight: gap within 2-day range = continuation not exhaustion; BTOH = time-based overheat protection; d<>LastTradeDay bars settlement entry.'},
{'source_file': 'E:/\u6295\u8cc7\u4ea4\u6613/pla_md/logic/Homework20201009 (2).md', 'strategy_name': 'Homework20201009_dup2', 'family': 'Homework series', 'timeframe': 'Intraday', 'direction': 'Both', 'category': 'Dual-session mid-price crossover stop entry (dup2)', 'summary': 'Homework20201009 (copy 2) -- Deduped.'},
{'source_file': 'E:/\u6295\u8cc7\u4ea4\u6613/pla_md/logic/Homework20201009.md', 'strategy_name': 'Homework20201009_base', 'family': 'Homework series', 'timeframe': 'Dual-session (day t=1140 / night t=0300)', 'direction': 'Both', 'category': 'Dual-session mid-price crossover and H/L breakout stop entry', 'summary': 'Homework20201009 (base) -- k<set-in: cross-L stop at h; cross-S stop at l. EntriesToday=0: night-stops at mid price. Time filters: t=1140, t=300, t<0500. Key insight: dual-session (day ends 1140, night ends 0300); mid = (H+L)/2 pivot between sessions; cross = H/L breakout mode; night stop = fade from overnight mid = mean-reversion for night session.'},
{'source_file': 'E:/\u6295\u8cc7\u4ea4\u6613/pla_md/logic/Homework20210204 (2).md', 'strategy_name': 'Homework20210204_dup2', 'family': 'Homework series', 'timeframe': 'Intraday', 'direction': 'Both', 'category': 'Fibonacci retracement entry with ATR stop and cooling/overheat exit (dup2)', 'summary': 'Homework20210204 (copy 2) -- Deduped.'},
{'source_file': 'E:/\u6295\u8cc7\u4ea4\u6613/pla_md/logic/Homework20210204.md', 'strategy_name': 'Homework20210204_base', 'family': 'Homework series', 'timeframe': 'Intraday (SetExitOnClose)', 'direction': 'Both', 'category': 'Fibonacci 0.618 retracement entry with ATR stop and dual cooling/overheat exit', 'summary': 'Homework20210204 (base) -- Long entry: (highD(1)*1+closeD(1)*0.618)/1.618 = Fib-weighted prior H+close. ATR SL: AvgTrueRange(300/barinterval)*COUNTDAY. Cooling exit: countif(o<c, 300/barinterval-1)<COLOR. Overheat exit: countif(o<c)>(300/barinterval-COLOR). JUMP gap filter. Key insight: 0.618 weighting = golden-ratio retracement entry; dual exit = clear both when cold AND overheated; 300/barinterval = session-normalized bar count.'},
{'source_file': 'E:/\u6295\u8cc7\u4ea4\u6613/pla_md/logic/homework20210612 (2).md', 'strategy_name': 'Homework20210612_dup2', 'family': 'Homework series', 'timeframe': 'Dual-session', 'direction': 'Both', 'category': 'Dual-session time-gate market entry (dup2)', 'summary': 'Homework20210612 (copy 2) -- Deduped.'},
{'source_file': 'E:/\u6295\u8cc7\u4ea4\u6613/pla_md/logic/homework20210612.md', 'strategy_name': 'Homework20210612_base', 'family': 'Homework series', 'timeframe': 'Dual-session (day t>0845 / night t<0300)', 'direction': 'Both', 'category': 'Dual-session time-gate market entry with 7-bar pre-session-end exit', 'summary': 'Homework20210612 (base) -- (t>0845 OR t<0300) AND count<1 -> market entry. Exit: calctime(sess2endtime,-7*barinterval). Key insight: OR on two time windows captures day-start AND night-end; count<1 = first entry only; 7-bar pre-night-exit provides more buffer than standard 1-bar.'},
{'source_file': 'E:/\u6295\u8cc7\u4ea4\u6613/pla_md/logic/homework20210612-\u4fee\u6b63.md', 'strategy_name': 'Homework20210612_revised', 'family': 'Homework series', 'timeframe': 'Dual-session (day t>=0845 / night t<0300)', 'direction': 'Both', 'category': 'Dual-session time-gate entry revised (>= includes 0845 bar)', 'summary': 'Homework20210612 revised -- t>0845 changed to t>=0845. Captures exact session-open bar for earlier fill potential.'},
{'source_file': 'E:/\u6295\u8cc7\u4ea4\u6613/pla_md/logic/Homework20210706.md', 'strategy_name': 'Homework20210706_base', 'family': 'Homework series', 'timeframe': 'Dual-session (day t>=0845 / night t<0300)', 'direction': 'Both', 'category': 'Dual-session time-gate market entry (0706 version, same as revised 0612)', 'summary': 'Homework20210706 -- Identical to 20210612-revised. Homework series systematically explores session timing as primary variable.'},
{'source_file': 'E:/\u6295\u8cc7\u4ea4\u6613/pla_md/logic/homework20210815 (2).md', 'strategy_name': 'Homework20210815_dup2', 'family': 'Homework series', 'timeframe': 'Dual-session', 'direction': 'Both', 'category': 'Five-mode adaptive strategy (dup2)', 'summary': 'Homework20210815 (copy 2) -- Deduped.'},
{'source_file': 'E:/\u6295\u8cc7\u4ea4\u6613/pla_md/logic/homework20210815.md', 'strategy_name': 'Homework20210815_base', 'family': 'Homework series', 'timeframe': 'Dual-session (t<1300 day / t>0400 night)', 'direction': 'Both', 'category': 'Five-mode: counter-trend, breakout, loss-reversal, doublewin scale-in, PM open entry', 'summary': 'Homework20210815 (base) -- Five modes: (1)counter closeadp 3-bar trend; (2)trend breakout stop at highadp/lowadp; (3)loss reversal stop order; (4)dubblewin: scale-in when count=1 AND key=0 (first win); (5)PM: t=sess2firstbartime -> market. SL: entryprice+/-n. Key insight: dubblewin = scale-in after first win not averaging down; PM separate entry captures overnight gap; closeadp = adaptive smoothed close.'},
{'source_file': 'E:/\u6295\u8cc7\u4ea4\u6613/pla_md/logic/homework20210907 (2).md', 'strategy_name': 'Homework20210907_dup2', 'family': 'Homework series', 'timeframe': 'Dual-session', 'direction': 'Both', 'category': 'Band breakout with adaptive stoploss-reversal (dup2)', 'summary': 'Homework20210907 (copy 2) -- Deduped.'},
{'source_file': 'E:/\u6295\u8cc7\u4ea4\u6613/pla_md/logic/homework20210907.md', 'strategy_name': 'Homework20210908_base', 'family': 'Homework series', 'timeframe': 'Dual-session (time<1335 / t<0400)', 'direction': 'Both', 'category': 'Band breakout with local-pivot entry and adaptive stoploss-reversal', 'summary': 'Homework20210908 (base) -- Long: stop at minlist(lowerband, lowest(l,2)+stp/2). Short: stop at maxlist(upperband, highest(h,2)-stp/2). Loss-reversal: if stop hit and new breakout confirms -> auto-reverse. Key insight: combining band with 2-bar local pivot = tighter fill; stoploss-reversal = aggressive auto-reverse not just exit; stp/2 buffer on local low.'},
{'source_file': 'E:/\u6295\u8cc7\u4ea4\u6613/pla_md/logic/Hsiang_TX_055_FDT_4min (2).md', 'strategy_name': 'Hsiang_TX_055_FDT_4min_dup2', 'family': 'Hsiang series', 'timeframe': '4min', 'direction': 'Both', 'category': 'Multi-factor breakout: OHLC ratio + amplitude gap + adaptive mean distance (dup2)', 'summary': 'Hsiang_TX_055_Q5_FDT_4min (copy 2) -- Deduped.'},
{'source_file': 'E:/\u6295\u8cc7\u4ea4\u6613/pla_md/logic/Hsiang_TX_055_FDT_4min (3).md', 'strategy_name': 'Hsiang_TX_055_FDT_4min_dup3', 'family': 'Hsiang series', 'timeframe': '4min', 'direction': 'Both', 'category': 'Multi-factor breakout (dup3)', 'summary': 'Hsiang_TX_055_Q5_FDT_4min (copy 3) -- Deduped.'},
{'source_file': 'E:/\u6295\u8cc7\u4ea4\u6613/pla_md/logic/Hsiang_TX_055_FDT_4min (4).md', 'strategy_name': 'Hsiang_TX_055_FDT_4min_dup4', 'family': 'Hsiang series', 'timeframe': '4min', 'direction': 'Both', 'category': 'Multi-factor breakout (dup4)', 'summary': 'Hsiang_TX_055_Q5_FDT_4min (copy 4) -- Deduped.'},
{'source_file': 'E:/\u6295\u8cc7\u4ea4\u6613/pla_md/logic/Hsiang_TX_055_FDT_4min.md', 'strategy_name': 'Hsiang_TX_055_Q5_FDT_4min_base', 'family': 'Hsiang series', 'timeframe': '4min (t>=0845 to t<1200)', 'direction': 'Both', 'category': 'Multi-factor 4min: OHLC ratio + amplitude + adaptive distance + descending-low acceleration', 'summary': 'Hsiang_TX_055_Q5_FDT_4min (base) -- Long: mp=0 AND dentry<=0 AND CONDITION31 -> stop at HIGHEST(H,N1). Short: L<HIGHADP-ratio*avgmaxdis; AmHighD/AmOpenD AM reference; l[1]-l>l[2]-l[1] AND l[2]-l[1]>0 = accelerating descent; HIGHEST(H,N1)<HIGHEST(H,N1)[N1]. SL: win_pts*0.8. Exit: c<entryprice-MAXLIST(50,opend*0.005); 2*AVERAGE(H-L,20) wick; time exit. Key insight: avgmaxdis/avggap = adaptive vol normalization; descending-low acceleration = momentum filter; 0.8*win_pts = R:R floor.'},
{'source_file': 'E:/\u6295\u8cc7\u4ea4\u6613/pla_md/logic/HsuanPin_TX_202109_FLT (2).md', 'strategy_name': 'HsuanPin_TX_202109_FLT_dup2', 'family': 'HsuanPin series', 'timeframe': 'Intraday', 'direction': 'Both', 'category': 'Weekly H/L breakout with Friday exit and last-week range target (dup2)', 'summary': 'HsuanPin_TX_202109_FLT (copy 2) -- Deduped.'},
{'source_file': 'E:/\u6295\u8cc7\u4ea4\u6613/pla_md/logic/HsuanPin_TX_202109_FLT.md', 'strategy_name': 'HsuanPin_TX_202109_FLT_base', 'family': 'HsuanPin series', 'timeframe': 'Intraday (t>=845 to t<=1330)', 'direction': 'Both', 'category': 'Weekly H/L pivot breakout with Friday mandatory exit and last-week range profit target', 'summary': 'HsuanPin_TX_202109_FLT (base) -- Long: DayOfWeek 1-5 AND t>=845-1330 -> stop at lpt-dpt. Exit: AmOpend<Amlowd(1) -> sell; win_pts>=hl_last_week AND c<o -> sell all; Friday -> Exit. Key insight: hl_last_week as dynamic PT = weekly range as natural holding measure; Friday mandatory exit = no weekend risk; AmOpend gap exit; weekday-only.'},
{'source_file': 'E:/\u6295\u8cc7\u4ea4\u6613/pla_md/logic/Hsuanpin_TX_202110_DT (2).md', 'strategy_name': 'Hsuanpin_TX_202110_DT_dup2', 'family': 'HsuanPin series', 'timeframe': 'Intraday', 'direction': 'Both', 'category': '2-day range breakout with gap-size qualifier (dup2)', 'summary': 'Hsuanpin_TX_202110_DT (copy 2) -- Deduped.'},
{'source_file': 'E:/\u6295\u8cc7\u4ea4\u6613/pla_md/logic/Hsuanpin_TX_202110_DT.md', 'strategy_name': 'Hsuanpin_TX_202110_DT_base', 'family': 'HsuanPin series', 'timeframe': 'Intraday (t<1300, t>=1325 exit)', 'direction': 'Both', 'category': '2-day HHLL range breakout with gap-to-range ratio qualifier (>33%)', 'summary': 'Hsuanpin_TX_202110_DT (base) -- HHLL=maxlist(HighD1,HighD0)-minlist(LowD1,LowD0); dis=maxlist(25,|openD2-closeD1|); Filter=dis/HHLL>0.333. Long: MP=0 AND EntriesToday=0 AND Filter -> stop at lowest(l,in)+bpts. Short: highest(h,in)-bpts. Key insight: dis/HHLL>0.333 = gap >33% of 2-day range = significant gap regime; bpts buffer for entry; filters flat days.'},
{'source_file': 'E:/\u6295\u8cc7\u4ea4\u6613/pla_md/logic/Hsuanpin_TX_CCI202201_FDT.md', 'strategy_name': 'Hsuanpin_TX_CCI202201_FDT_base', 'family': 'HsuanPin series', 'timeframe': 'Intraday (t>=900-1330 / night t>=0230-0500)', 'direction': 'Both', 'category': 'CCI-based Donchian channel entry with session-mode toggle', 'summary': 'Hsuanpin_TX_CCI202201_FDT (base) -- Value3=(highest(h,HLLen)+lowest(l,HLLen))/2 = Donchian midpoint. CCI(cLen). Long: Daytradetime=1 -> stop at lpt. Short: MP<=0 AND l_cci>LBand -> stop at spt. Key insight: Donchian midpoint as reference; l_cci>LBand = CCI above lower band = not oversold before shorting; Daytradetime toggle for session; separate day/night exit labels.'},
{'source_file': 'E:/\u6295\u8cc7\u4ea4\u6613/pla_md/logic/Hsuanpin_TX_KD202111_FlT.md', 'strategy_name': '_Hsuanpin_TX_KD202111_FLT_base', 'family': 'HsuanPin series', 'timeframe': '60min (night 2100/2200, day >=0900)', 'direction': 'Both', 'category': 'KD 60min adaptive-close breakout with Donchian midpoint cross exit and ATR stop', 'summary': '_Hsuanpin_TX_KD202111_FLT (base) -- Value3=(highest(h,len)+lowest(l,len))/2 = Donchian midpoint. KD(12,3,3,1). ATR SL: AvgTrueRange(600/barinterval)*stopprofit. BullCondition -> Long: stop at maxlist(highadp,closeadp[1]). Exit: price cross under Value3 -> sell. DayOfWeek filter. Key insight: 600/barinterval = timeframe-agnostic ATR; highadp/closeadp = adaptive smooth prices; cross-midpoint = Donchian regime reversal exit.'},
{'source_file': 'E:/\u6295\u8cc7\u4ea4\u6613/pla_md/logic/HW010_TX_ CDP Entropy_5M_FDT.md', 'strategy_name': 'TX_CDP_Entropy_5M_FDT_base', 'family': 'HW workshop series', 'timeframe': '5min (day t>=0845 t<1500 / night t>=1500)', 'direction': 'Both', 'category': 'CDP with entropy regime-filter for dual-session multi-mode breakout/reversion', 'summary': 'TX_CDP_Entropy_5M_FDT (base) -- CDP: AH/NH/AL/NL. entropy<0.5 = low = orderly market = trend mode. entropy>=0.5 = high = disorder = reversion mode. Day L1/S1: condition AND entropy<0.5 -> market. S2: entropy>=0.5 AND Dentry=0 = high-entropy short. Night entries: calibrated stop at Night_O+(NH-CDP)/2. Reversal: mp<0->RL at Highada; mp>0->RS at Lowada. Timeout exit at T=1330. Key insight: entropy as regime switch between trend and reversion; Night_O+(NH-CDP)/2 = half the NH-CDP distance above night open.'},
{'source_file': 'E:/\u6295\u8cc7\u4ea4\u6613/pla_md/logic/HW012_TX_ HL Wap & Jump out_5M_DT (2).md', 'strategy_name': 'TX_HLWap_Jump_5M_DT_dup2', 'family': 'HW series', 'timeframe': '5min', 'direction': 'Both', 'category': 'H_L VWAP jump-gap breakout with CountIf-weighted entry (dup2)', 'summary': 'TX_HLWap & Jump out_5M_DT (copy 2) -- Deduped.'},
{'source_file': 'E:/\u6295\u8cc7\u4ea4\u6613/pla_md/logic/HW012_TX_ HL Wap & Jump out_5M_DT.md', 'strategy_name': 'TX_HLWap_Jump_5M_DT_base', 'family': 'HW series', 'timeframe': '5min (T<1300, exit t>=1335)', 'direction': 'Both', 'category': 'H_L VWAP jump-gap: CountIf majority-bar regime switches entry level + tightening SL', 'summary': 'TX_HLWap & Jump out_5M_DT (base) -- H_L_wap = daily H and L weighted average price midpoint. L1: IFF(CountIf(C>O,K)>=K/2, (LowD+OpenD)/2, HighD). If majority bullish -> enter at open-low mid; else day high. L2: jump AND majority -> (HighD+H_L_wap)/2 or HighD. SL: entryprice-STL+barssinceentry (tightening). Key insight: H_L_wap fairer intraday reference; CountIf switches entry level = regime-adaptive; tightening SL = stop tightens with time.'},
{'source_file': 'E:/\u6295\u8cc7\u4ea4\u6613/pla_md/logic/HW013_TX_ NO DH&DL in_3M_DT.md', 'strategy_name': 'TX_NO_DH_DL_in_3M_DT_base', 'family': 'HW series', 'timeframe': '3min (T<1200 / T>1200 reversal)', 'direction': 'Both', 'category': 'No daily-H/L touch 3min: contextual IFF entry + summation bull/bear ratio', 'summary': 'TX_NO_DH_DL_in_3M_DT (base) -- Entry excludes bars at daily H or L. L1: IFF(HighD0>HighD1 OR FirstK_H<LowD1, (HighD0*2+OpenD)/3, (OpenD+HighD1)/2). Tightening SL. Limit exit CloseD(1)*1.09. Summation(C-L,K) vs Summation(H-C,K) = bull/bear effort ratio. DCAVG3=(C1+C2+C3+Open0)/4. Key insight: contextual IFF entry based on today vs prior H; FirstK_H = opening range; summation ratio = intraday bull/bear effort comparison.'},
{'source_file': 'E:/\u6295\u8cc7\u4ea4\u6613/pla_md/logic/HW013_TX_K bar break out_17M_FLT+.md', 'strategy_name': 'TX_Kbar_breakout_17M_FLTplus_base', 'family': 'HW series', 'timeframe': 'Intraday (t>=0845 day / t>=1500 night / exit>=1334)', 'direction': 'Both', 'category': 'Adaptive K-bar breakout: prior-bar bearish/bullish selects entry level', 'summary': 'TX_Kbar_breakout_17M_FLT+ (base) -- L1: IFF(closeada(1)<openada(1), highada(1), Highadp(0)) = if prior bearish -> prior bar adaptive high; if bullish -> today adaptive high. L2: highada(0). S1/S2 mirrors. Key insight: bearish prior bar -> resistance at prior high = the level to break; bullish prior -> today high is natural breakout; L1+L2 = pyramiding structure.'},
{'source_file': 'E:/\u6295\u8cc7\u4ea4\u6613/pla_md/logic/Ivan2109_TX_DV6k_DT_ver2.md', 'strategy_name': 'Ivan2109_TX_DV6k_DT_ver2_base', 'family': 'Ivan series', 'timeframe': 'Intraday (t<0900 night / t<1320 day / t<1500 hard)', 'direction': 'Both', 'category': 'Volatility-regime tri-mode breakout: sqrt-price SL + count-adjusted dynamic target', 'summary': 'Ivan2109_TX_DV6k_DT_ver2 (base) -- CT_L: sess1firstbartime -> stop at (AmOpenD+AmHighD)/2. T_L: mean<prior close -> stop at AmOpenD. BH: DayVolatility(3,20)<-(2/3)*DayVolatility(3,31) = very low vol mode. SL: entryprice-power(price,0.5)-k-barssinceentry = sqrt(price)+k+bars. Dynamic target: highest(C,...)+CountIf(c-o>0,...). Key insight: sqrt(price) SL = price-proportional stop; low-vol regime detection; count-adjusted breakout target self-adapts to momentum.'},
{'source_file': 'E:/\u6295\u8cc7\u4ea4\u6613/pla_md/logic/Ivan2109_TX_DV6k_DT_ver2 (2).md', 'strategy_name': 'Ivan2109_TX_DV6k_DT_ver2_dup2', 'family': 'Ivan series', 'timeframe': 'Intraday', 'direction': 'Both', 'category': 'Volatility-regime tri-mode breakout with sqrt-price SL (dup2)', 'summary': 'Ivan2109_TX_DV6k_DT_ver2 (copy 2) -- Deduped.'},
{'source_file': 'E:/\u6295\u8cc7\u4ea4\u6613/pla_md/logic/J_BB1_0621 (2).md', 'strategy_name': 'J_BB1_4min_FDT_dup2', 'family': 'J/BBand series', 'timeframe': '4min', 'direction': 'Both', 'category': 'BB on gap-adjusted close with ATR stop and H/L touch-count tracking (dup2)', 'summary': 'J_BB1_4min_FDT (copy 2) -- Deduped.'},
{'source_file': 'E:/\u6295\u8cc7\u4ea4\u6613/pla_md/logic/J_BB1_0621 (3).md', 'strategy_name': 'J_BB1_4min_FDT_dup3', 'family': 'J/BBand series', 'timeframe': '4min', 'direction': 'Both', 'category': 'BB on gap-adjusted close (dup3)', 'summary': 'J_BB1_4min_FDT (copy 3) -- Deduped.'},
{'source_file': 'E:/\u6295\u8cc7\u4ea4\u6613/pla_md/logic/J_BB1_0621 (4).md', 'strategy_name': 'J_BB1_4min_FDT_dup4', 'family': 'J/BBand series', 'timeframe': '4min', 'direction': 'Both', 'category': 'BB on gap-adjusted close (dup4)', 'summary': 'J_BB1_4min_FDT (copy 4) -- Deduped.'},
{'source_file': 'E:/\u6295\u8cc7\u4ea4\u6613/pla_md/logic/J_BB1_0621.md', 'strategy_name': 'J_BB1_4min_FDT_base', 'family': 'J/BBand series', 'timeframe': '4min (dual-session)', 'direction': 'Both', 'category': 'BB on gap-adjusted close: ATR stop, 6-bar range protection, H/L touch-count tracking', 'summary': 'J_BB1_4min_FDT (base) -- BB computed on (close-gap) = removes overnight jump bias. Long: stop at upBB+gap. Short: downBB+gap. SL: ATR(k)*3. Exit: c<entryprice; TM-S_Day. CountIf(h=EntryH,barssinceentry)-CountIf(l=entryL,barssinceentry) = net touch balance. Highest/Lowest(6) protective stop. Key insight: gap-adjusted BB removes jump contamination; ATR(k)*3 = 3x session ATR; touch-count = sticky price analysis.'},
{'source_file': 'E:/\u6295\u8cc7\u4ea4\u6613/pla_md/logic/J_Bband1118.md', 'strategy_name': 'J_BBand_100min_LT_base', 'family': 'J/BBand series', 'timeframe': 'Long-term 100min (t>1230, settlement-aware)', 'direction': 'Both', 'category': 'BB trend-following with 3-bar MA-cross entry and dual settlement avoidance guards', 'summary': 'J_BBand_100min_LT (base) -- Long B1: not _afterSettThurs AND d<>CalcDate(LastTradeDay,-1) AND highest(h,3) cross over avg. Short S1: highest(h,3) cross under avg. Limit exit: maxlist(BB(-2),entryprice-150). Daily reversal exit: openD(1)>highD(2) AND openD(1)>closeD(1) AND closeD(1)>c. Key insight: _afterSettThurs = skip 2 days before settlement (options expiry); 3-bar H/L MA-cross = momentum confirmation; gap-reversal exit; double settlement protection.'},
{'source_file': 'E:/\u6295\u8cc7\u4ea4\u6613/pla_md/logic/Jeremy_Work.md', 'strategy_name': 'Jeremy_TX_25m_work2101_base', 'family': 'Jeremy series', 'timeframe': 'Intraday (kday>1)', 'direction': 'Both', 'category': 'EMA-filtered daily H/L breakout with 1,3,5-day triple-lookback trend confirmation', 'summary': 'Jeremy_TX_25m_work2101 (base) -- Long B01: kday>1 AND EntriesToday=0 AND k>=in -> stop at HighD(0). SL/PT: fixed 100pts. XAverage(c,300) macro trend. condition1: closeD0>HighD1 AND closeD0>HighD3 AND closeD0>highD5. Exit BX5: openD0<closeD1 AND c<MA300 -> sell. Key insight: 1,3,5-day H series = compounding trend confirmation; symmetric 1:1 RR; BX5 = gap-down + below 300 EMA = macro trend breakdown.'},
{'source_file': 'E:/\u6295\u8cc7\u4ea4\u6613/pla_md/logic/JeremyWork_30TX_Week_LOS (2).md', 'strategy_name': 'Jeremywork_30TX_Week_LOS_dup2', 'family': 'Jeremy series', 'timeframe': 'Intraday', 'direction': 'Both', 'category': 'Weekly range breakout with gap-reversal exit (dup2)', 'summary': 'Jeremywork_30TX_Week_LOS (copy 2) -- Deduped.'},
{'source_file': 'E:/\u6295\u8cc7\u4ea4\u6613/pla_md/logic/JeremyWork_30TX_Week_LOS.md', 'strategy_name': 'Jeremywork_30TX_Week_LOS_base', 'family': 'Jeremy series', 'timeframe': 'Intraday (t>=0945 to t<=1315)', 'direction': 'Both', 'category': 'N-bar range breakout with gap-reversal, gap-below-prior-low stop, and prior-close exit modes', 'summary': 'Jeremywork_30TX_Week_LOS (base) -- Long B1: condition40 AND mp=0 AND EntriesToday=0 AND d<>LastTradeDay -> stop at highest(h,len). Short S1: stop at lowest(L,len). Reversal SX3: mp<0 AND openD<closeD(1) AND c>closeD(1) -> buytocover. BX1: openD<lowD(1) -> stop at lowD(1). BX2: openD>closeD(1) AND c<closeD(1) -> market. Key insight: likely weekly-range len; gap below prior low = danger stop at lowD(1); SX3 = short covering on gap-down recovery; settlement exclusion.'},
{'source_file': 'E:/\u6295\u8cc7\u4ea4\u6613/pla_md/logic/Jeremy-work07 (2).md', 'strategy_name': 'Jeremya2dwork07_dup2', 'family': 'Jeremy series', 'timeframe': 'Settlement day only', 'direction': 'Both', 'category': 'Settlement-day PSY filtered 2-bar breakout with 9% circuit-breaker exit (dup2)', 'summary': 'Jeremy-work07 (copy 2) -- Deduped.'},
{'source_file': 'E:/\u6295\u8cc7\u4ea4\u6613/pla_md/logic/Jeremy-work07.md', 'strategy_name': 'Jeremya2dwork07_base', 'family': 'Jeremy series', 'timeframe': 'Settlement day (d=LastTradeDay)', 'direction': 'Both', 'category': 'Settlement-day PSY psychological line with 2-bar breakout and 9% circuit-breaker exit', 'summary': 'Jeremy-work07 (base) -- PSY=Summation(n,len)/len*100 = % up bars (Psychological Line). condition1: PSY>60; condition2: PSY<40. Long B1: d=LastTradeDay AND h>HighD(1) -> stop at HIGHEST(H,2). Exit BX3: h>=closeD(1)*1.09 -> sell. SX3: l<=closeD(1)*0.91 -> buytocover. Key insight: PSY = Japanese TA; settlement-day only exploits pinning/unwinding; PSY bias before settlement breakout; 9% = circuit-breaker analog exit.'},
{'source_file': 'E:/\u6295\u8cc7\u4ea4\u6613/pla_md/logic/JOSEPHXY198_TX_AVERAGEPRICE6K_LT(20220104).md', 'strategy_name': 'JOSEPHXY198_TX_AVERAGEPRICE6K_LT_20220104', 'family': 'Joseph series', 'timeframe': 'Intraday (always active)', 'direction': 'Both', 'category': 'Rolling average VWAP proxy with % bias and CountIf lower-low scale-in', 'summary': 'JOSEPHXY198_TX_AVERAGEPRICE6K_LT (20220104) -- dayprice=Average(value2,k) = dynamic intraday VWAP proxy. hbias/lbias = % from dayprice. Long: mp=0 AND EntriesToday<=0 AND c>=lowD(1) AND c>=o -> market. Scale: iff(countif(l<l[1],k)>=k*0.5, 2, 1). Exit: c<(lpoint+lowD(1))/2 -> sell. Key insight: rolling average as VWAP proxy; % bias normalized distance; scale when majority bars making lower lows; exit at support-zone midpoint.'},
{'source_file': 'E:/\u6295\u8cc7\u4ea4\u6613/pla_md/logic/JOSEPHXY198_TX_KD15K(20210610)_LT(20210806V4).md', 'strategy_name': 'JOSEPHXY198_TX_KD15K_LT_V4', 'family': 'Joseph series', 'timeframe': 'Intraday (t>0900, t>=1330 exit)', 'direction': 'Both', 'category': 'FastK extreme + range expansion + HA reference + bad-entry self-evaluation exit', 'summary': 'JOSEPHXY198_TX_KD15K (LT V4) -- FastK(kdlen). countb=countif(kdkvalue<20,10). condition3: range>=2*ATR = expansion. haClose=(O+H+L+C)/4. Entry: stop at h or l; back-hand reversal. SL: range-based; ratio-trail. Bad-entry: barssinceentry>=9 AND c<avg -> market exit. Key insight: range expansion = breakout regime only; bad-entry self-correction after 9 bars; HA close for smooth regime; ratio-trail = progressive profit lock.'},
{'source_file': 'E:/\u6295\u8cc7\u4ea4\u6613/pla_md/logic/KCCCI.md', 'strategy_name': 'khsu_CFExTest_202010_KcCCI_base', 'family': 'khsu series', 'timeframe': 'Intraday (CalcTime session gates)', 'direction': 'Both', 'category': 'Keltner Channel + CCI all-bars persistence breakout with recency decay filter', 'summary': 'khsu_CFExTest202010_KcCCI (base) -- Keltner: ma1+/-KCMulti*ATR. CCI(KCLen). condition11: countif(CCI>100 AND h>upper, strNBars)>=strNBars = ALL bars above upper Keltner with CCI>100. currentbar-shortableBar<KCLen = recency gate. Long: session gates -> stop at maxlist(HighD(0),buyPrice). Short: condition11 AND c<dnner -> stop at minlist(lowD(0),shortPrice). Key insight: ALL-bars persistence = very strong confirmation; Keltner ATR-based more stable than BB; recency gate keeps signal fresh; CCI>100 fade for short.'},
{'source_file': 'E:/\u6295\u8cc7\u4ea4\u6613/pla_md/logic/KE_EDIT.md', 'strategy_name': 'KE001_StdDev_squeeze_breakout', 'family': 'KE series', 'timeframe': 'Intraday (t<=1345, settlement guard)', 'direction': 'Both', 'category': 'StdDev volatility squeeze breakout with Typical Price and settlement precision guard', 'summary': 'KE001 -- avgDCS=Average(TypicalPrice,lenL). Squeeze: StdDev(typicalprice,lenL)<StdDev(typicalprice,lenL*2) = compression. Long: not (IsSettlementDay AND t>=calctime(1230,-bar) AND t<=1345) -> stop at Highest(h,lenL). Short: -> stop at Lowest(l,lenS). Key insight: explicit StdDev ratio = Bollinger Squeeze analog; Typical Price series; settlement guard blocks only final ~1hr of settlement; asymmetric lenL vs lenS.'},
{'source_file': 'E:/\u6295\u8cc7\u4ea4\u6613/pla_md/logic/khsu_202007.md', 'strategy_name': 'khsu_CFExTest202007_QIndicatorLaddar_base', 'family': 'khsu series', 'timeframe': '6min (exit t>=1330)', 'direction': 'Both', 'category': 'Custom Q-indicator ladder momentum breakout with adaptive P&L-based entry frequency', 'summary': 'khsu_CFExTest202007_QIndicatorLaddar (base) -- accumulation=summation(C-C[1],3). Qindicator custom normalized. laddarLine1=lowest(l,laddarStep) = step-function ladder. Long L1/L2: k>in AND k<notin AND EntriesToday<=iff(positionprofit(1)>0,1,2) -> stop at highest(h,2) or highD(0). leadLaddar<yesLaddar AND countif(Qindicator>Qindicator[1],3)=2 = ladder rising + Q momentum. Key insight: ladder = moving step-function support; adaptive entry limit: max 1 after profit/max 2 after loss = frequency management; 3-bar momentum accumulator.'},
{'source_file': 'E:/\u6295\u8cc7\u4ea4\u6613/pla_md/logic/khsu_202007_WF (2).md', 'strategy_name': 'khsu_CFExTest202007_QIndicatorLaddar_WF_dup2', 'family': 'khsu series', 'timeframe': '6min', 'direction': 'Both', 'category': 'Q-indicator ladder momentum WF version (dup2)', 'summary': 'khsu_CFExTest202007_QIndicatorLaddar_WF (copy 2) -- Walk-Forward variant. Same core logic. Deduped.'},
]

outfile = 'C:/Users/admin/workspace/digital-immortality/results/digestion_log.jsonl'
with open(outfile, 'a', encoding='utf-8') as f:
    for e in entries:
        row = {'timestamp': ts, 'batch': batch, 'source_file': e['source_file'], 'strategy_name': e['strategy_name'], 'family': e['family'], 'timeframe': e['timeframe'], 'direction': e['direction'], 'category': e['category'], 'summary': e['summary']}
        f.write(json.dumps(row, ensure_ascii=False) + '\n')
print('Written', len(entries), 'entries')
