import json

entries = [
    {"file":"E:/投資交易/pla_md/function/dayatr3.md","type":"function","name":"dayatr3","modified":"2018-05-30","summary":"Custom Day ATR function. Loops over Length days, computes True Range as max of 4 combinations of high/low across consecutive days, returns average. More robust than standard ATR: uses 4-way max (H-L), (H[1]-L[1]), (H[1]-L), (H-L[1]) across consecutive day pairs. Useful for day-level volatility normalization.","tags":["ATR","volatility","function","day-data"],"concepts":["true-range","volatility-normalization","daily-ATR"]},
    {"file":"E:/投資交易/pla_md/function/LSEScore.md","type":"function","name":"LSEScore","modified":"2025-03-16","summary":"Custom fitness/optimization scoring function. Formula: (OpenEquity / AvgDrawdown) * sqrt(Trades/30) * (TotalMFE^2) / (TotalMAE * MaxMAE * TotalTrades). Balances return vs drawdown vs MAE/MFE efficiency. Normalizes by trade count (sqrt factor vs 30 trades baseline). MaxMAE penalizes worst-case adverse excursion. Requires daily ATR normalization of MFE/MAE via GetDayATR(5). Companion helpers: CloseS1/HighS1/LowS1 (session OHLC lookback), OHLCPeriodsAgoS (circular buffer), GetDayATR.","tags":["fitness","optimization","MFE","MAE","drawdown","function"],"concepts":["walk-forward","portfolio-optimization","risk-adjusted-return","MAE-MFE-analysis"]},
    {"file":"E:/投資交易/pla_md/function/MagicADLuckyNet.md","type":"function","name":"_MagicADLuckyNet","modified":"2019-09-12","summary":"Advanced MagicLuckyNet. Dual-signal: PriceMoveA = future vs index spread direction; PriceMoveB = open-gap continuation. Filters 1-9 progressively add: dividend adjustment (Jun-Sep, DivAdjust by EA ratio for FITX/FITE/FITF), trend filter (MA8/MA21), prevDay H/L breakout confirmation, MACD, ADX>30. Night session: if 70% of intraday bars agree on direction carry as NightMove. Daytime (0845-1345) uses PriceMove, outside uses NightMove. CheckPeriod covers hardcoded high-volatility date ranges (2015-2019).","tags":["mean-reversion","trend-filter","futures-spot-spread","function","index-arbitrage","seasonal"],"concepts":["futures-spot-spread","dividend-seasonality","night-session","ADX-filter","MACD-filter"]},
    {"file":"E:/投資交易/pla_md/function/MagicLuckyNet.md","type":"function","name":"_MagicLuckyNet","modified":"2018-07-06","summary":"Base MagicLuckyNet. Two core signals: PriceMoveA (futures close vs index close - future cheaper than index yields long bias=1); PriceMoveB (gap continuation: close>open and open>prevClose = bullish). Filters 1-9 add dividend adj for Jun-Sep (30/40/50 pts), trend filter via MA8/MA21, prevDay H/L breakout, MACD(12,26), ADX(12)>30. Symbol detection auto-scales DivAdjust by EA multiplier (FITE=24.5, FITF=9.15). Returns +1/0/-1 direction signal.","tags":["mean-reversion","futures-spot-spread","function","index-arbitrage","seasonal","dividend"],"concepts":["futures-spot-spread","dividend-seasonality","gap-continuation","signal-generation"]},
    {"file":"E:/投資交易/pla_md/function/QQ.md","type":"function","name":"QQ","modified":"2022-02-16","summary":"Hardcoded date-lookup table for Taiwan futures options time-value (2007-2020). Values represent daily option time premium remaining before settlement. Counts down from ~100-250 at cycle start to 0 at settlement day, then resets. Each monthly cycle starts high post-settlement and decays to 0. Used as extrinsic value / theta reference. Settlement resets occur mid-month (3rd Wednesday, Taiwan futures rules).","tags":["options","theta","settlement","function","time-decay","Taiwan-futures"],"concepts":["option-time-value","settlement-cycle","theta-decay","Taiwan-futures-options"]},
    {"file":"E:/投資交易/pla_md/function/set.md","type":"function","name":"_Settlement","modified":"2018-05-31","summary":"Boolean function returning true on Taiwan futures settlement day. Primary rule: day 15-21, Wednesday (DayOfWeek=3). Fallback: if no Wednesday in that range, accepts Thu-Tue progressively (days 16-22+). Uses value1 as monthly flag to prevent double-trigger. Resets each new month. Core utility referenced by many strategies for settlement-day position management.","tags":["settlement","function","Taiwan-futures","calendar"],"concepts":["settlement-detection","monthly-reset","day-of-week"]},
    {"file":"E:/投資交易/pla_md/function/SFoder.md","type":"function","name":"SFoder","modified":"2024-03-29","summary":"Price tick rounding function. Applies Taiwan stock market tick size rules: 10-50 = 0.05 tick, 50-100 = 0.10 tick, 100-500 = 0.50 tick, 500-1000 = 1.0 tick, 1000+ = 5.0 tick. Uses mod() with midpoint rounding (rounds up if remainder > half-tick). Returns rounded price matching exchange minimum tick increments.","tags":["utility","tick-size","price-rounding","function","Taiwan-stocks"],"concepts":["tick-size","price-normalization","market-microstructure"]},
    {"file":"E:/投資交易/pla_md/function/Today_Is_Settle_Day.md","type":"function","name":"_Today_Is_Settle_Day","modified":"2020-11-07","summary":"Robust settlement day detection. Tracks LastSettleDay via persistent state. Detects: primary = Wed day 15-21; fallback = consecutive weekdays (Thu day 16+, Fri 17+, Sat 18+, Sun/Mon 19-20+, Tue 21+, Wed 22+) only if current month differs from LastSettleDay month. Returns boolean True/False.","tags":["settlement","function","Taiwan-futures","calendar"],"concepts":["settlement-detection","persistent-state","monthly-cycle"]},
    {"file":"E:/投資交易/pla_md/function/如意多空網 MagicQF001.md","type":"function","name":"_MagicQF001","modified":"2018-07-03","summary":"Simplified core of MagicLuckyNet. Filter=1: futures vs index direction (future below index = bullish=1). Filter=2: open-gap continuation (close>open and open>prevClose = bullish). Returns +1/0/-1. Base building block for MagicNet family. Intraday uses live close; overnight uses CloseD(1) comparison.","tags":["futures-spot-spread","function","signal","index-arbitrage"],"concepts":["futures-spot-spread","gap-continuation","signal-generation"]},
    {"file":"E:/投資交易/pla_md/indicator/DonChianChannel_Indicator.md","type":"indicator","name":"DonchianChannel","modified":"2021-07-02","summary":"Standard Donchian Channel indicator. Plots Highest(base, Length) as upper band, Lowest(base, Length) as lower band, optional midline average. Default length=13, base=close. Used for breakout detection and trend-following entries.","tags":["breakout","channel","indicator","Donchian"],"concepts":["price-channel","breakout","trend-following"]},
    {"file":"E:/投資交易/pla_md/indicator/DonChianChannel_Indicator (2).md","type":"indicator","name":"DonchianChannel_dup2","modified":"2021-07-02","summary":"Duplicate of DonchianChannel indicator. See DonChianChannel_Indicator.md.","tags":["breakout","channel","indicator","Donchian","duplicate"],"concepts":["price-channel","breakout"]},
    {"file":"E:/投資交易/pla_md/indicator/DonChianChannel_Indicator (3).md","type":"indicator","name":"DonchianChannel_dup3","modified":"2021-07-02","summary":"Duplicate of DonchianChannel indicator. See DonChianChannel_Indicator.md.","tags":["breakout","channel","indicator","Donchian","duplicate"],"concepts":["price-channel","breakout"]},
    {"file":"E:/投資交易/pla_md/indicator/DonChianChannel_Indicator (4).md","type":"indicator","name":"DonchianChannel_dup4","modified":"2021-07-02","summary":"Duplicate of DonchianChannel indicator. See DonChianChannel_Indicator.md.","tags":["breakout","channel","indicator","Donchian","duplicate"],"concepts":["price-channel","breakout"]},
    {"file":"E:/投資交易/pla_md/indicator/EMA_Indicator.md","type":"indicator","name":"EMA_Indicator","modified":"2021-07-02","summary":"Standard EMA indicator using XAverage(). Supports Displace parameter for shifted display. Alerts on EMA turning up (price>EMA and slope positive) or turning down (price<EMA and slope negative). Default length=9. Basic trend-direction tool.","tags":["MA","EMA","indicator","trend"],"concepts":["moving-average","trend-direction","slope-detection"]},
    {"file":"E:/投資交易/pla_md/indicator/EMA_Indicator (2).md","type":"indicator","name":"EMA_Indicator_dup2","modified":"2021-07-02","summary":"Duplicate of EMA indicator. See EMA_Indicator.md.","tags":["MA","EMA","indicator","trend","duplicate"],"concepts":["moving-average"]},
    {"file":"E:/投資交易/pla_md/indicator/EMA_Indicator (3).md","type":"indicator","name":"EMA_Indicator_dup3","modified":"2021-07-02","summary":"Duplicate of EMA indicator. See EMA_Indicator.md.","tags":["MA","EMA","indicator","trend","duplicate"],"concepts":["moving-average"]},
    {"file":"E:/投資交易/pla_md/indicator/EMA_Indicator (4).md","type":"indicator","name":"EMA_Indicator_dup4","modified":"2021-07-02","summary":"Duplicate of EMA indicator. See EMA_Indicator.md.","tags":["MA","EMA","indicator","trend","duplicate"],"concepts":["moving-average"]},
    {"file":"E:/投資交易/pla_md/indicator/Exponente-Hurst.md","type":"indicator","name":"Hurst_Exponent","modified":"2023-04-11","summary":"Hurst Exponent indicator via R/S (rescaled range) method over Len bars. Mean-centers prices, builds cumulative sum series, tracks range (MaxY-MinY) and std deviation. H = log(R/(k*S)) / log(Len) where k=1.253314. H>0.5 = trending/persistent, H<0.5 = mean-reverting, H=0.5 = random. Reference line at 0.5 plotted. Used for regime detection before applying trend vs mean-reversion strategy.","tags":["Hurst","regime-detection","indicator","statistics"],"concepts":["Hurst-exponent","R/S-analysis","trending-vs-mean-reverting","regime-classification"]},
    {"file":"E:/投資交易/pla_md/indicator/freeman_daytrade_indicator.md","type":"indicator","name":"freeman_daytrade_cost_line","modified":"2021-08-16","summary":"Intraday session range analysis indicator. Tracks session H/L, plots cost_line = (sessionH+sessionL)/2. Maintains rolling 20-session range array, classifies as small (<avg) or large (>=avg). Plots 5 target levels from session low (long targets: min/small/avg/large/max range) and 5 from session high (short targets). Resets at session start (modes: 0=0845, 1=0500, 2=both). Used for intraday mean-reversion target placement.","tags":["intraday","session-range","indicator","mean-reversion","targets"],"concepts":["session-midpoint","range-classification","target-levels","cost-of-carry-line"]},
    {"file":"E:/投資交易/pla_md/indicator/Mid.md","type":"indicator","name":"ShowDayMID","modified":"2020-10-11","summary":"Prior-day pivot midpoint indicator. Formula: (HighD(1) + LowD(1) + CloseD(1)*2) / 4. Updates once per day at bar open. Weighted toward close (double weight). Used as intraday support/resistance reference.","tags":["pivot","indicator","support-resistance","daily-midpoint"],"concepts":["weighted-pivot","prior-day-reference","support-resistance"]},
    {"file":"E:/投資交易/pla_md/indicator/Mid (2).md","type":"indicator","name":"ShowDayMID_dup2","modified":"2020-10-11","summary":"Duplicate of Mid.md pivot indicator. See Mid.md.","tags":["pivot","indicator","support-resistance","duplicate"],"concepts":["weighted-pivot"]},
    {"file":"E:/投資交易/pla_md/indicator/OrderMaster.md","type":"indicator","name":"OrderMaster","modified":"2018-07-26","summary":"Multi-signal position aggregator and order router. Reads up to 30 named global variables (GV) keyed by filename+number, sums them for net position. On settlement day outside 0845-1340 sets position to 0 (flatten). Writes net position + current price to text file via DLL for external order execution. Key architecture: GlobalVariable.dll for inter-chart communication, file-based order bridge to execution system. Settlement helper: LastTradeDay() finds 3rd Wednesday of month.","tags":["order-management","position","system-architecture","indicator","DLL","multi-signal"],"concepts":["signal-aggregation","global-variable-bus","file-based-order-routing","settlement-flatten"]},
    {"file":"E:/投資交易/pla_md/indicator/readFile.md","type":"indicator","name":"readFile_TEST","modified":"2017-04-15","summary":"Test indicator for ELCollections DLL file-reading utility. Reads up to 4 text files each containing 8 numeric values. Uses ListN_New/ReadFile/Get/Clear pattern from ELCollections_x64.dll. Demonstrates file-based data injection into TradeStation from external processes.","tags":["utility","file-IO","indicator","DLL","external-data"],"concepts":["external-data-injection","file-IO","DLL-interface"]},
    {"file":"E:/投資交易/pla_md/indicator/三大法人籌碼運用 指標.md","type":"indicator","name":"三大法人籌碼NET-OI","modified":"2018-12-29","summary":"Taiwan three institutional investors (三大法人) net OI indicator. Reads 6 data streams (data2-data7) representing long/short positions of 3 institutions. value1=sum of all long positions, value2=sum of all short positions, value3=net (long-short). Plots long in magenta, short in cyan, net in red/green. Used to gauge institutional positioning bias for directional trading.","tags":["institutional","OI","indicator","Taiwan-futures","three-institutions"],"concepts":["institutional-positioning","net-open-interest","market-sentiment","Taiwan-specific"]},
    {"file":"E:/投資交易/pla_md/logic/!_TXDD_1_003_TXEX2104.md","type":"strategy","name":"a39130_TX_20210406_DO","classification":"Day Trading","direction":"Both","summary":"TX day-trade strategy. Long L1: breakout condition32; L2: condition21 + position check + avgprice below channel lower zone (Highest+Lowest*2)/3. Short S1: condition32; S2: condition12 + close above avgc + avgprice above upper zone (Highest*2+Lowest)/3. Dynamic channel uses Highest(C,k) and Lowest(C,k). Stop loss via SetStopLoss(stp). Uses 3-day average daily range for avgl filter. Time filter: 1000-1300. SetExitOnClose.","tags":["TX","breakout","day-trade","channel","stop-loss"],"concepts":["channel-breakout","dynamic-zones","daily-range-filter","intraday-session"]},
    {"file":"E:/投資交易/pla_md/logic/!_TXDD_1_006_TXEX2106.md","type":"strategy","name":"_TXex_DT_6mk_202106","classification":"Day Trading","direction":"Both","summary":"TX day-trade with gap-open logic. Long: gap up (OpenD>CloseD(1)*(1+ratio)) uses stop at (highd(0)+L)/2 else at C. Short: symmetric gap-down. Pyramid entries up to 3/day (barssinceentry>3) at entryprice+stp stop. Re-entry at Highest(h,5)/Lowest(l,5) stop. Time filter: t<1330. SetExitOnClose. Key: distinguishes gap-open direction for asymmetric entry levels.","tags":["TX","gap","day-trade","pyramid","stop-order"],"concepts":["gap-open","directional-entry","pyramid-scaling","barssinceentry"]},
    {"file":"E:/投資交易/pla_md/logic/!_TXDL_1_060_TXEX2107.md","type":"strategy","name":"a3997","classification":"Trend Following / Breakout","direction":"Both","summary":"TX trend/breakout with StdDev-based channel. Entry: condition31 (stddev/amplitude filter) + mp=0 + not session end -> buy stop at Highest(H, stdLen*0.5), sell stop at Lowest(L, stdLen*0.5). Exit: trailing stops using daily H/L ranges (MaxList(highd(0),highd(1)) vs entryprice+AvgRange(H-L,k)). avgprice vs (C[1]+C)*0.5 as directional filter. LastTradeDay detection for settlement management.","tags":["TX","trend","breakout","stddev","trailing-stop"],"concepts":["stddev-channel","half-period-breakout","trailing-daily-range","settlement-management"]},
    {"file":"E:/投資交易/pla_md/logic/$@LV_lowebar_jump_11K_LT.md","type":"strategy","name":"c24c40LV_TX_lowBar_jump_11K_LT","classification":"Swing / Long-Term","direction":"Both","summary":"TX swing strategy using pivot midpoint levels. Entry: mp=0 + condition31 -> stop order. Profit target: long at MinList(L, openD(0)); short at MaxList(H, openD(0)). Exit at market on signal. Mid pivot = (highd(1)+lowd(1)+closedD(1)*2)/4; up=mid*2-lowd(1); dn=mid*2-highd(1). Gap analysis vs prior day. K-bar pattern detection. Time filter: t>=1330 or 2 bars before session end.","tags":["TX","swing","pivot","kbar-pattern","profit-target"],"concepts":["pivot-midpoint","overnight-gap","profit-target-at-session-open","swing-entry"]},
    {"file":"E:/投資交易/pla_md/logic/$@LV_lowebar_jump_11K_LT (2).md","type":"strategy","name":"c24c40LV_TX_lowBar_jump_11K_LT_dup2","classification":"Swing / Long-Term","direction":"Both","summary":"Duplicate of $@LV_lowebar_jump_11K_LT. See parent entry.","tags":["TX","swing","pivot","duplicate"],"concepts":["pivot-midpoint","swing-entry"]},
    {"file":"E:/投資交易/pla_md/logic/$2106K06_TX_BBand_LO_60K.md","type":"strategy","name":"c242106K06_TX_BBand_LO","classification":"Day Trading","direction":"Both","summary":"Complex TX day-trade combining Bollinger Bands + RSI + ATR. Long: close crosses above BBand upper (CountIf(c>HB,1)=1) + high>=dh(session high) + high < lowd(0)+ATR*ATRratio + condition99 -> stop at Highest(h,3)+1. RSI reversal entry (RsirevL1): RSI drops from >=RsiRatio. Exit: fixed stop at entryprice+/-STPL; large adverse bar exit (O-C>ATR*2.5 and C<entry); RSI reversal exit. Time: sess1firstbartime+in*barinterval to sess1endtime-barinterval. condition99 prevents entry near EMA300. ATR cap on entry distance from daily extreme.","tags":["TX","BBand","RSI","ATR","day-trade","breakout","reversal"],"concepts":["bollinger-breakout","RSI-reversal","ATR-extension-filter","EMA300-trend-filter","fixed-stop"]},
    {"file":"E:/投資交易/pla_md/logic/$2106K06_TX_BBand_LO_60K (2).md","type":"strategy","name":"c242106K06_TX_BBand_LO_dup2","classification":"Day Trading","direction":"Both","summary":"Duplicate of $2106K06_TX_BBand_LO_60K. See parent entry.","tags":["TX","BBand","RSI","ATR","day-trade","duplicate"],"concepts":["bollinger-breakout","RSI-reversal"]},
    {"file":"E:/投資交易/pla_md/logic/$2106K06_TX_BBand_LO_60K (3).md","type":"strategy","name":"c242106K06_TX_BBand_LO_dup3","classification":"Day Trading","direction":"Both","summary":"Duplicate of $2106K06_TX_BBand_LO_60K. See parent entry.","tags":["TX","BBand","RSI","ATR","day-trade","duplicate"],"concepts":["bollinger-breakout","RSI-reversal"]},
]

output_path = "C:/Users/admin/workspace/digital-immortality/results/digestion_log.jsonl"
with open(output_path, "a", encoding="utf-8") as f:
    for entry in entries:
        f.write(json.dumps(entry, ensure_ascii=False) + "\n")

print(f"Appended {len(entries)} entries to digestion_log.jsonl")
