#!/usr/bin/env python3
"""
stale_detector_run.py — Daily wrapper for stale_detector.py

Runs the canonical stale memory scan and writes a dated markdown report to
C:/Users/admin/staging/stale_detector_<YYYYMMDD>.md

Called by Windows Task Scheduler task "Edward_StaleMemory_Check" daily at 03:00.
Can also be called by the L3 selfmod system or daemon via:
    python tools/stale_detector_run.py

Exit codes:
    0 — no stale files
    1 — stale files found (flagged, not deleted)
    2 — error running scan
"""
from __future__ import annotations

import sys
from datetime import datetime
from pathlib import Path
from zoneinfo import ZoneInfo

TPE = ZoneInfo("Asia/Taipei")

# Ensure platform/ is importable
REPO_ROOT = Path(__file__).resolve().parent.parent
PLATFORM = REPO_ROOT / "platform"
if str(PLATFORM) not in sys.path:
    sys.path.insert(0, str(PLATFORM))

STAGING = Path("C:/Users/admin/staging")


def main() -> int:
    try:
        from stale_detector import scan_memory_files, MEMORY_DIR, STALE_THRESHOLD_DAYS
    except ImportError as exc:
        print(f"[stale_detector_run] Import error: {exc}", file=sys.stderr)
        return 2

    now = datetime.now(tz=TPE)
    date_str = now.strftime("%Y%m%d")
    report_path = STAGING / f"stale_detector_{date_str}.md"

    try:
        results = scan_memory_files()
    except FileNotFoundError as exc:
        print(f"[stale_detector_run] Scan error: {exc}", file=sys.stderr)
        return 2

    stale_items = [r for r in results if r["stale"]]
    unreferenced = [r for r in results if not r["referenced"] and not r["stale"]]
    ok_count = len(results) - len(stale_items)

    # --- Build report ---
    lines: list[str] = [
        f"# Stale Memory Detector — Run Report",
        f"**Date**: {now.strftime('%Y-%m-%d %H:%M +08')}",
        f"**Script**: `{PLATFORM / 'stale_detector.py'}`",
        f"**Directory**: `{MEMORY_DIR}`",
        f"**Threshold**: {STALE_THRESHOLD_DAYS} days since last_modified AND not referenced in MEMORY.md",
        "",
        "---",
        "",
    ]

    if not stale_items:
        lines += [
            f"## Result: 0 STALE FILES",
            "",
            f"Total files scanned: {len(results)}",
            f"Stale (flagged): 0",
            f"OK (current or referenced): {ok_count}",
            "",
            "All memory files are either modified within the last 30 days or referenced in MEMORY.md.",
        ]
    else:
        lines += [
            f"## Result: {len(stale_items)} STALE FILE(S) FLAGGED",
            "",
            f"Total files scanned: {len(results)}",
            f"Stale (flagged): {len(stale_items)}",
            f"OK (current or referenced): {ok_count}",
            "",
            "**Action required**: Review the flagged files. Do NOT delete without verifying they",
            "are truly unused. If still relevant, add them to MEMORY.md to clear the flag.",
            "",
            "### Flagged Stale Files",
            "",
            "| Filename | Last Modified | Referenced |",
            "|----------|--------------|------------|",
        ]
        for r in stale_items:
            lines.append(f"| {r['filename']} | {r['last_modified']} | {'YES' if r['referenced'] else 'NO'} |")

    if unreferenced:
        lines += [
            "",
            "---",
            "",
            f"## Unreferenced Files (watch list — not yet stale)",
            "",
            "These files are NOT in MEMORY.md but are within the 30-day window.",
            "They will become stale candidates if not referenced before the cutoff date.",
            "",
            "| Filename | Last Modified | Days Remaining |",
            "|----------|--------------|----------------|",
        ]
        for r in unreferenced:
            from datetime import datetime as dt2
            from zoneinfo import ZoneInfo as ZI2
            mtime = dt2.fromisoformat(r["last_modified"].replace(" +08", "+08:00"))
            age_days = (now - mtime).days
            days_left = STALE_THRESHOLD_DAYS - age_days
            lines.append(f"| {r['filename']} | {r['last_modified']} | {days_left} days |")

    lines += [
        "",
        "---",
        "",
        "## Integration Notes",
        "",
        "- Canonical script: `platform/stale_detector.py`",
        "- Scheduled via: Windows Task Scheduler `Edward_StaleMemory_Check` (daily 03:00 +08)",
        "- Can also be invoked from L3 selfmod: `python tools/stale_detector_run.py`",
        "- Or via daemon: `python platform/recursive_daemon.py --l3-check` (l3_selfmod handles broader checks)",
        "",
        f"*Generated by stale_detector_run.py at {now.strftime('%Y-%m-%d %H:%M +08')}*",
    ]

    STAGING.mkdir(parents=True, exist_ok=True)
    report_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"[stale_detector_run] Report written: {report_path}")
    print(f"[stale_detector_run] Scanned {len(results)} files | Stale: {len(stale_items)} | Unreferenced: {len(unreferenced)}")

    return 1 if stale_items else 0


if __name__ == "__main__":
    sys.exit(main())
